### ISSUE TITLE
일기 작성 페이지 타입 적용

### ISSUE THREAD

**Issue by YoungseoChoi23** [MoodBuddy/MoodBuddy-Web-TS#13]
## Description
일기 작성 페이지 타입 적용

## To-do
- [ ] TopBar 타입 적용
- [ ] Diary 타입 적용
- [ ] 감정 분석 모달창 타입 적용
- [ ] 템플릿 타입 적용
- [ ] 임시저장 모달창 타입 적용
