### ISSUE TITLE
END POINT 설정 및 Api, Axios 기본 설정

### ISSUE THREAD

**Issue by m2na7** [MoodBuddy/MoodBuddy-Web-TS#7]
## Description
END POINT 적용 

## To-do
- [x] END_POINT.ts 
- [x] apis 엔드포인트 변경
- [x] 기존 api 타입 지정
- [x] Axios 타입 지정
